pub const SCHEMA_VERSION: u32 = 1;
pub const CATALOG_VERSION: &str = "1.0.0";
pub const MANIFEST_PATH: &str = "fixtures/operation-catalog.toml";
pub const DOCS_PATH: &str = "docs/operation-catalog.md";
pub const SUPPORT_MATRIX_PATH: &str = "docs/operation-support-matrix.md";

/// Immutable operation identities.  `entry_id` is the parity-facing name and
/// `operation_id` is the consumer-facing stable key; changing either mapping
/// is a compatibility event rather than an ordinary catalog edit.
pub const OPERATION_ID_BASELINE: &[(&str, &str)] = &[
    ("doctor", "op.doctor"),
    ("scripts", "op.scripts"),
    ("describe", "op.describe"),
    ("history-list", "op.history-list"),
    ("history-show", "op.history-show"),
    ("history-traces", "op.history-traces"),
    ("history-stats", "op.history-stats"),
    ("queue-add", "op.queue-add"),
    ("queue-cancel", "op.queue-cancel"),
    ("queue-dead-letter", "op.queue-dead-letter"),
    ("env-list", "op.env-list"),
    ("env-create", "op.env-create"),
    ("env-show", "op.env-show"),
    ("env-replace", "op.env-replace"),
    ("env-set", "op.env-set"),
    ("env-remove", "op.env-remove"),
    ("env-activate", "op.env-activate"),
    ("env-deactivate", "op.env-deactivate"),
    ("env-delete", "op.env-delete"),
    ("battery-list", "op.battery-list"),
    ("battery-inspect", "op.battery-inspect"),
    ("battery-scripts", "op.battery-scripts"),
    ("battery-remove", "op.battery-remove"),
    ("node-init", "op.node-init"),
    ("node-status", "op.node-status"),
    ("node-peers", "op.node-peers"),
    ("node-trust", "op.node-trust"),
    ("node-capabilities", "op.node-capabilities"),
    ("node-revoke", "op.node-revoke"),
    ("node-health", "op.node-health"),
    ("node-signals", "op.node-signals"),
    ("node-baseline-push", "op.node-baseline-push"),
    ("node-baseline-rollback", "op.node-baseline-rollback"),
    ("node-enroll-approve", "op.node-enroll-approve"),
    ("node-enroll-reject", "op.node-enroll-reject"),
    ("config", "op.config"),
    ("search", "op.search"),
    ("battery-add", "op.battery-add"),
    ("battery-sync", "op.battery-sync"),
    ("battery-install", "op.battery-install"),
    ("node-discovery", "op.node-discovery"),
    ("node-cue", "op.node-cue"),
    ("node-enroll-request", "op.node-enroll-request"),
    ("http-node-enrollments", "op.http-node-enrollments"),
    ("node-enroll-apply", "op.node-enroll-apply"),
    ("http-health", "op.http-health"),
    ("http-ready", "op.http-ready"),
    ("http-admin-status", "op.http-admin-status"),
    ("http-workspace", "op.http-workspace"),
    ("http-tree-root", "op.http-tree-root"),
    ("http-tree-path", "op.http-tree-path"),
    ("http-secrets", "op.http-secrets"),
    ("cli-api", "op.cli-api"),
    ("cli-completion", "op.cli-completion"),
    ("cli-help-ai", "op.cli-help-ai"),
    ("cli-history-tail", "op.cli-history-tail"),
    ("cli-init", "op.cli-init"),
    ("cli-node-authority-create", "op.cli-node-authority-create"),
    ("cli-node-authority-issue", "op.cli-node-authority-issue"),
    ("cli-node-authority-show", "op.cli-node-authority-show"),
    (
        "cli-node-baseline-create-key",
        "op.cli-node-baseline-create-key",
    ),
    ("cli-node-baseline-publish", "op.cli-node-baseline-publish"),
    ("cli-node-direct-probe", "op.cli-node-direct-probe"),
    ("cli-node-reset", "op.cli-node-reset"),
    ("cli-node-serve", "op.cli-node-serve"),
    ("cli-queue-worker", "op.cli-queue-worker"),
    ("cli-run", "op.cli-run"),
    ("cli-serve", "op.cli-serve"),
    ("cli-token-generate", "op.cli-token-generate"),
    ("cli-trace", "op.cli-trace"),
    ("cli-uninstall", "op.cli-uninstall"),
    ("cli-update", "op.cli-update"),
];
