//! `omakure help-ai` — single-call AI capability discovery.
//!
//! Always emits JSON. The flags/subcommands list is generated by walking
//! `Cli::command()` so it cannot drift from `--help`.

use crate::cli::args::Cli;
use crate::cli::json::{self, SCHEMA_VERSION};
use clap::CommandFactory;
use serde::Serialize;
use serde_json::{json, Value};
use std::error::Error;

#[derive(Debug, Serialize)]
pub struct HelpAiPayload {
    pub schema_version: &'static str,
    pub trust_model: &'static str,
    pub envelope: Value,
    pub error_codes: Vec<&'static str>,
    pub verbs: Vec<VerbInfo>,
    pub data_shapes: Value,
}

#[derive(Debug, Serialize)]
pub struct VerbInfo {
    pub name: String,
    pub about: String,
    pub flags: Vec<FlagInfo>,
    pub subcommands: Vec<SubcommandInfo>,
}

#[derive(Debug, Serialize)]
pub struct FlagInfo {
    pub long: Option<String>,
    pub short: Option<char>,
    pub help: String,
    pub takes_value: bool,
    pub required: bool,
}

#[derive(Debug, Serialize)]
pub struct SubcommandInfo {
    pub name: String,
    pub about: String,
    pub flags: Vec<FlagInfo>,
}

const TRUST_MODEL: &str = "AI is a full user; everything is audited. \
No allowlists, denylists, or per-script confirmation gates. Every run \
is recorded in .history/runs.sqlite with actor, optional reason, full \
argv, exit code, stdout, stderr, start/end timestamps, and a stable run_id.";

const AI_VERBS: &[&str] = &[
    "scripts",
    "describe",
    "search",
    "run",
    "init",
    "history",
    "config",
    "help-ai",
];

pub fn run() -> Result<(), Box<dyn Error>> {
    let payload = build_payload();
    json::print_ok(payload);
    Ok(())
}

fn build_payload() -> HelpAiPayload {
    let cmd = Cli::command();
    let verbs = collect_verbs(&cmd);

    HelpAiPayload {
        schema_version: SCHEMA_VERSION,
        trust_model: TRUST_MODEL,
        envelope: json!({
            "ok": "bool",
            "data": "any",
            "error": {
                "code": "string (one of error_codes)",
                "message": "string (human readable)",
            },
            "schema_version": SCHEMA_VERSION,
        }),
        error_codes: vec![
            "not_found",
            "schema_invalid",
            "script_exists",
            "missing_required_field",
            "invalid_argument",
            "not_implemented",
            "internal",
        ],
        verbs,
        data_shapes: json!({
            "scripts": crate::cli::describe::sample_envelope(), // describe shape doubles as a per-script summary example
            "describe": crate::cli::describe::sample_envelope(),
            "search": crate::cli::describe::sample_envelope(),
            "run": json!({
                "ok": true,
                "data": {
                    "run_id": "<unix_ms>-<pid>-<counter>",
                    "script_path": "/abs/path/to/script.sh",
                    "script_name": null,
                    "args_json": "[\"--target\",\"prod\"]",
                    "actor": "ai",
                    "reason": "rolling out config",
                    "started_at": 1700000000000_i64,
                    "finished_at": 1700000001234_i64,
                    "duration_ms": 1234,
                    "exit_code": 0,
                    "success": true,
                    "stdout": "...",
                    "stderr": "",
                    "error": null,
                    "parent_run_id": null,
                    "omakure_version": "0.1.7"
                },
                "error": null,
                "schema_version": SCHEMA_VERSION,
            }),
            "history_list": json!({
                "ok": true,
                "data": [
                    {
                        "run_id": "<id>",
                        "script_path": "/abs/path",
                        "script_name": null,
                        "args_json": "[]",
                        "actor": "ai",
                        "reason": null,
                        "started_at": 1700000000000_i64,
                        "finished_at": 1700000000123_i64,
                        "duration_ms": 123,
                        "exit_code": 0,
                        "success": true,
                        "error": null,
                        "parent_run_id": null,
                        "omakure_version": "0.1.7"
                    }
                ],
                "error": null,
                "schema_version": SCHEMA_VERSION,
            }),
            "history_show": "Same shape as `run` data above (full RunRow including stdout/stderr).",
            "config": json!({
                "ok": true,
                "data": {
                    "version": "0.1.7",
                    "binary": "/usr/local/bin/omakure",
                    "workspace_root": "/home/me/Documents/omakure-scripts",
                    "scripts_root": "/home/me/Documents/omakure-scripts",
                    "history_dir": "/home/me/Documents/omakure-scripts/.history",
                    "envs_dir": "/home/me/Documents/omakure-scripts/.omaken/envs",
                    "active_env": null,
                    "bootstrap_mode": "plain",
                    "env_overrides": {}
                },
                "error": null,
                "schema_version": SCHEMA_VERSION,
            }),
        }),
    }
}

fn collect_verbs(cmd: &clap::Command) -> Vec<VerbInfo> {
    let mut out = Vec::new();
    for sub in cmd.get_subcommands() {
        let name = sub.get_name().to_string();
        if !AI_VERBS.contains(&name.as_str()) {
            continue;
        }
        out.push(VerbInfo {
            name: name.clone(),
            about: sub
                .get_about()
                .map(|s| s.to_string())
                .unwrap_or_default(),
            flags: collect_flags(sub),
            subcommands: collect_nested(sub),
        });
    }
    out
}

fn collect_flags(cmd: &clap::Command) -> Vec<FlagInfo> {
    cmd.get_arguments()
        .filter(|a| !a.is_positional())
        .map(|a| FlagInfo {
            long: a.get_long().map(|s| s.to_string()),
            short: a.get_short(),
            help: a
                .get_help()
                .map(|s| s.to_string())
                .unwrap_or_default(),
            takes_value: a.get_action().takes_values(),
            required: a.is_required_set(),
        })
        .collect()
}

fn collect_nested(cmd: &clap::Command) -> Vec<SubcommandInfo> {
    cmd.get_subcommands()
        .map(|sub| SubcommandInfo {
            name: sub.get_name().to_string(),
            about: sub
                .get_about()
                .map(|s| s.to_string())
                .unwrap_or_default(),
            flags: collect_flags(sub),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn payload_lists_all_ai_verbs() {
        let payload = build_payload();
        let names: Vec<&str> = payload.verbs.iter().map(|v| v.name.as_str()).collect();
        for verb in AI_VERBS {
            // help-ai is itself an AI verb but appears in clap as `help-ai`.
            assert!(
                names.contains(verb),
                "verb {} should appear in help-ai payload, got {:?}",
                verb,
                names
            );
        }
    }

    #[test]
    fn payload_carries_schema_version() {
        let payload = build_payload();
        assert_eq!(payload.schema_version, "1");
    }

    #[test]
    fn payload_lists_error_codes() {
        let payload = build_payload();
        assert!(payload.error_codes.contains(&"not_found"));
        assert!(payload.error_codes.contains(&"schema_invalid"));
        assert!(payload.error_codes.contains(&"script_exists"));
        assert!(payload.error_codes.contains(&"missing_required_field"));
    }

    #[test]
    fn history_subcommand_exposes_list_show_tail() {
        let payload = build_payload();
        let history = payload
            .verbs
            .iter()
            .find(|v| v.name == "history")
            .expect("history verb present");
        let nested: Vec<&str> = history.subcommands.iter().map(|s| s.name.as_str()).collect();
        assert!(nested.contains(&"list"));
        assert!(nested.contains(&"show"));
        assert!(nested.contains(&"tail"));
    }
}
