//! `omakure help-ai` — single-call AI capability discovery.
//!
//! Always emits JSON. The flags/subcommands list is generated by walking
//! `Cli::command()` so it cannot drift from `--help`.

use crate::cli::inventory::{command_inventory, InventoryCommand, InventoryOption};
use crate::cli::json::{self, SCHEMA_VERSION};
use serde::Serialize;
use serde_json::{json, Value};
use std::collections::BTreeMap;
use std::error::Error;

#[derive(Debug, Serialize)]
pub struct HelpAiPayload {
    pub schema_version: &'static str,
    pub trust_model: &'static str,
    pub envelope: Value,
    pub error_codes: Vec<&'static str>,
    pub verbs: Vec<VerbInfo>,
    pub data_shapes: Value,
}

#[derive(Debug, Serialize)]
pub struct VerbInfo {
    pub name: String,
    pub about: String,
    pub flags: Vec<FlagInfo>,
    pub subcommands: Vec<SubcommandInfo>,
}

#[derive(Debug, Serialize)]
pub struct FlagInfo {
    pub id: String,
    pub long: Option<String>,
    pub short: Option<char>,
    pub aliases: Vec<String>,
    pub hidden_aliases: Vec<String>,
    pub help: String,
    pub positional: bool,
    pub takes_value: bool,
    pub required: bool,
    pub default_values: Vec<String>,
    pub value_names: Vec<String>,
    pub possible_values: Vec<String>,
    pub min_values: Option<usize>,
    pub max_values: Option<usize>,
    pub action: String,
    pub global: bool,
    pub hidden: bool,
    pub deprecated: bool,
}

#[derive(Debug, Serialize)]
pub struct SubcommandInfo {
    pub id: String,
    pub name: String,
    pub about: String,
    pub aliases: Vec<String>,
    pub hidden_aliases: Vec<String>,
    pub hidden: bool,
    pub deprecated: bool,
    pub flags: Vec<FlagInfo>,
    pub subcommands: Vec<SubcommandInfo>,
}

const TRUST_MODEL: &str = "AI is a full user; everything is audited. \
No allowlists, denylists, or per-script confirmation gates. Every run \
is recorded in .history/runs.sqlite with actor, optional reason, full \
argv, exit code, stdout, stderr, start/end timestamps, and a stable run_id.";

const AI_VERBS: &[&str] = &[
    "scripts", "describe", "search", "run", "init", "history", "queue", "battery", "token", "api",
    "trace", "config", "node", "help-ai",
];

pub fn run() -> Result<(), Box<dyn Error>> {
    let payload = build_payload();
    json::print_ok(payload);
    Ok(())
}

fn build_payload() -> HelpAiPayload {
    let verbs = collect_verbs();

    HelpAiPayload {
        schema_version: SCHEMA_VERSION,
        trust_model: TRUST_MODEL,
        envelope: json!({
            "ok": "bool",
            "data": "any",
            "error": {
                "code": "string (one of error_codes)",
                "message": "string (human readable)",
            },
            "schema_version": SCHEMA_VERSION,
        }),
        error_codes: vec![
            "not_found",
            "schema_invalid",
            "script_exists",
            "missing_required_field",
            "invalid_argument",
            "invalid_input",
            "unauthorized",
            "not_implemented",
            "internal",
            "already_exists",
            "not_synced",
            "manifest_invalid",
            "unsafe_path",
            "unsupported_script",
            "conflict",
            "git_failed",
            "io_failed",
            "registry_invalid",
            "payload_too_large",
        ],
        verbs,
        data_shapes: json!({
            "scripts": crate::cli::describe::sample_envelope(), // describe shape doubles as a per-script summary example
            "describe": crate::cli::describe::sample_envelope(),
            "search": crate::cli::describe::sample_envelope(),
            "run": json!({
                "ok": true,
                "data": {
                    "run_id": "<unix_ms>-<pid>-<counter>",
                    "script_path": "/abs/path/to/script.sh",
                    "script_name": null,
                    "args_json": "[\"--target\",\"prod\"]",
                    "actor": "ai",
                    "reason": "rolling out config",
                    "started_at": 1700000000000_i64,
                    "finished_at": 1700000001234_i64,
                    "duration_ms": 1234,
                    "exit_code": 0,
                    "success": true,
                    "stdout": "...",
                    "stderr": "",
                    "error": null,
                    "parent_run_id": null,
                    "omakure_version": "0.1.7"
                },
                "error": null,
                "schema_version": SCHEMA_VERSION,
            }),
            "history_list": json!({
                "ok": true,
                "data": [
                    {
                        "run_id": "<id>",
                        "script_path": "/abs/path",
                        "script_name": null,
                        "args_json": "[]",
                        "actor": "ai",
                        "reason": null,
                        "started_at": 1700000000000_i64,
                        "finished_at": 1700000000123_i64,
                        "duration_ms": 123,
                        "exit_code": 0,
                        "success": true,
                        "error": null,
                        "parent_run_id": null,
                        "omakure_version": "0.1.7"
                    }
                ],
                "error": null,
                "schema_version": SCHEMA_VERSION,
            }),
            "history_show": "Same shape as `run` data above (full RunRow including stdout/stderr).",
            "api": json!({
                "transport": "HTTP loopback/internal management API",
                "auth": "Authorization: Bearer <token>; prefer OMAKURE_TOKENS_FILE/--tokens-file (per-token scopes); legacy OMAKURE_API_TOKEN = id legacy scopes * gated by --capability (admin:status needs explicit capability); /v1/health and /v1/ready unauthenticated; GET /v1/admin/status needs admin:status (or * / capability all); 401 and authenticated requests emit omakure.http_audit (token_id never Authorization); --capability all does not bypass --secret-ref",
                "envelope": "Same { ok, data, error, schema_version } shape as CLI JSON.",
                "body_limit": "1 MiB",
                "reference": "docs/http-api.md",
            }),
            "config": json!({
                "ok": true,
                "data": {
                    "version": "0.1.7",
                    "binary": "/usr/local/bin/omakure",
                    "workspace_root": "/home/me/Documents/omakure-scripts",
                    "scripts_root": "/home/me/Documents/omakure-scripts",
                    "history_dir": "/home/me/Documents/omakure-scripts/.history",
                    "envs_dir": "/home/me/Documents/omakure-scripts/.omakure/envs",
                    "active_env": null,
                    "bootstrap_mode": "plain",
                    "env_overrides": {}
                },
                "error": null,
                "schema_version": SCHEMA_VERSION,
            }),
            "node": "Public node status, bounded trust-neutral LAN discovery, explicit initialization, bounded peer listing, current fleet health for trusted peers, the bounded newest-first closed Signal feed (enrolled, revoked, run-completed only), confirmed trust mutations, and dispatch of one authorized Cue asking a trusted Performer to run a script that Performer already declared; a Cue names a script and never carries one, so it cannot introduce code, and the outcome arrives as an ordinary run-completed Signal. Fleet health also reports each Performer's baseline as unknown, none, in_sync, or drifted, which is a comparison of two facts the Performer reports and never a verdict it sends. A signed baseline is published on a node that holds a publisher key and can therefore conduct nobody, is delivered by a Conductor that holds no key, and installs as one set or not at all; rolling a machine back onto the one previous version it retained is a local act on that machine and no peer can order it. Private identity material, discovery secrets, script arguments, run output, and audit history are never returned.",
        }),
    }
}

fn collect_verbs() -> Vec<VerbInfo> {
    let entries = command_inventory();
    let by_id: BTreeMap<&str, &InventoryCommand> = entries
        .iter()
        .map(|entry| (entry.id.as_str(), entry))
        .collect();

    AI_VERBS
        .iter()
        .filter_map(|name| {
            let entry = by_id.get(name)?;
            Some(VerbInfo {
                name: entry.name.clone(),
                about: entry.about.clone(),
                flags: collect_flags(entry),
                subcommands: collect_nested(entry, &by_id),
            })
        })
        .collect()
}

fn collect_flags(command: &InventoryCommand) -> Vec<FlagInfo> {
    command
        .options
        .iter()
        .filter(|option| !option.positional && !option.hidden)
        .map(flag_info)
        .collect()
}

fn flag_info(option: &InventoryOption) -> FlagInfo {
    FlagInfo {
        id: option.id.clone(),
        long: option.long.clone(),
        short: option.short,
        aliases: option.aliases.clone(),
        hidden_aliases: option.hidden_aliases.clone(),
        help: option.help.clone(),
        positional: option.positional,
        takes_value: option.takes_value,
        required: option.required,
        default_values: option.default_values.clone(),
        value_names: option.value_names.clone(),
        possible_values: option
            .possible_values
            .iter()
            .map(|value| value.name.clone())
            .collect(),
        min_values: option.min_values,
        max_values: option.max_values,
        action: option.action.clone(),
        global: option.global,
        hidden: option.hidden,
        deprecated: option.deprecated,
    }
}

fn collect_nested(
    command: &InventoryCommand,
    by_id: &BTreeMap<&str, &InventoryCommand>,
) -> Vec<SubcommandInfo> {
    command
        .subcommands
        .iter()
        .filter_map(|id| {
            let entry = by_id.get(id.as_str())?;
            Some(SubcommandInfo {
                id: entry.id.clone(),
                name: entry.name.clone(),
                about: entry.about.clone(),
                aliases: entry.aliases.clone(),
                hidden_aliases: entry.hidden_aliases.clone(),
                hidden: entry.hidden,
                deprecated: entry.deprecated,
                flags: collect_flags(entry),
                subcommands: collect_nested(entry, by_id),
            })
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn payload_lists_all_ai_verbs() {
        let payload = build_payload();
        let names: Vec<&str> = payload.verbs.iter().map(|v| v.name.as_str()).collect();
        for verb in AI_VERBS {
            // help-ai is itself an AI verb but appears in clap as `help-ai`.
            assert!(
                names.contains(verb),
                "verb {} should appear in help-ai payload, got {:?}",
                verb,
                names
            );
        }
    }

    #[test]
    fn payload_carries_schema_version() {
        let payload = build_payload();
        assert_eq!(payload.schema_version, "1");
    }

    #[test]
    fn payload_lists_error_codes() {
        let payload = build_payload();
        assert!(payload.error_codes.contains(&"not_found"));
        assert!(payload.error_codes.contains(&"schema_invalid"));
        assert!(payload.error_codes.contains(&"script_exists"));
        assert!(payload.error_codes.contains(&"missing_required_field"));
        assert!(payload.error_codes.contains(&"payload_too_large"));
    }

    #[test]
    fn history_subcommand_exposes_list_show_tail() {
        let payload = build_payload();
        let history = payload
            .verbs
            .iter()
            .find(|v| v.name == "history")
            .expect("history verb present");
        let nested: Vec<&str> = history
            .subcommands
            .iter()
            .map(|s| s.name.as_str())
            .collect();
        assert!(nested.contains(&"list"));
        assert!(nested.contains(&"show"));
        assert!(nested.contains(&"tail"));
    }

    #[test]
    fn node_inventory_is_recursive_through_three_levels() {
        let payload = build_payload();
        let node = payload
            .verbs
            .iter()
            .find(|verb| verb.name == "node")
            .unwrap();
        let baseline = node
            .subcommands
            .iter()
            .find(|command| command.name == "baseline")
            .unwrap();
        assert!(baseline
            .subcommands
            .iter()
            .any(|command| command.id == "node baseline publish"));

        let enroll = node
            .subcommands
            .iter()
            .find(|command| command.name == "enroll")
            .unwrap();
        assert!(enroll
            .subcommands
            .iter()
            .any(|command| command.id == "node enroll approve"));

        let authority = node
            .subcommands
            .iter()
            .find(|command| command.name == "authority")
            .unwrap();
        assert!(authority
            .subcommands
            .iter()
            .any(|command| command.id == "node authority issue"));
    }

    #[test]
    fn nested_flags_include_new_correlation_and_secret_references() {
        let payload = build_payload();
        let queue = payload
            .verbs
            .iter()
            .find(|verb| verb.name == "queue")
            .unwrap();
        let add = queue
            .subcommands
            .iter()
            .find(|command| command.name == "add")
            .unwrap();
        assert!(add
            .flags
            .iter()
            .any(|flag| flag.long.as_deref() == Some("run-id")));

        let battery = payload
            .verbs
            .iter()
            .find(|verb| verb.name == "battery")
            .unwrap();
        let add = battery
            .subcommands
            .iter()
            .find(|command| command.name == "add")
            .unwrap();
        assert!(add
            .flags
            .iter()
            .any(|flag| flag.long.as_deref() == Some("token-ref")));
    }

    #[test]
    fn public_help_ai_omits_hidden_options() {
        let payload = build_payload();
        let queue = payload
            .verbs
            .iter()
            .find(|verb| verb.name == "queue")
            .unwrap();
        let worker = queue
            .subcommands
            .iter()
            .find(|command| command.name == "worker")
            .unwrap();
        assert!(!worker
            .flags
            .iter()
            .any(|flag| flag.long.as_deref() == Some("once")));
    }

    #[test]
    fn explicit_ai_allowlist_does_not_widen_to_doctor() {
        let payload = build_payload();
        assert!(!payload.verbs.iter().any(|verb| verb.name == "doctor"));
    }
}
