/// Canonical `(method, path)` inventory for the HTTP management API.
///
/// Keep this list in lockstep with `router_with_policy`. Black-box E2E tests
/// compare the markers below with router registrations so route drift fails
/// the suite.
// OMAKURE_HTTP_ROUTE_INVENTORY_START
pub const HTTP_ROUTE_INVENTORY: &[(&str, &str)] = &[
    ("GET", "/v1/health"),
    ("GET", "/v1/ready"),
    ("GET", "/v1/admin/status"),
    ("GET", "/v1/config"),
    ("GET", "/v1/doctor"),
    ("GET", "/v1/workspace"),
    ("GET", "/v1/search"),
    ("GET", "/v1/tree"),
    ("GET", "/v1/tree/{*path}"),
    ("GET", "/v1/scripts"),
    ("GET", "/v1/scripts/{*script_id}"),
    ("GET", "/v1/envs"),
    ("POST", "/v1/envs"),
    ("DELETE", "/v1/envs/active"),
    ("GET", "/v1/envs/{name}"),
    ("PUT", "/v1/envs/{name}"),
    ("PATCH", "/v1/envs/{name}"),
    ("DELETE", "/v1/envs/{name}"),
    ("POST", "/v1/envs/{name}/activate"),
    ("PUT", "/v1/envs/{name}/params/{key}"),
    ("DELETE", "/v1/envs/{name}/params/{key}"),
    ("GET", "/v1/runs"),
    ("POST", "/v1/runs"),
    ("GET", "/v1/runs/{run_id}"),
    ("GET", "/v1/runs/{run_id}/traces"),
    ("POST", "/v1/runs/{run_id}/cancel"),
    ("POST", "/v1/runs/{run_id}/dead-letter"),
    ("GET", "/v1/queue/stats"),
    ("GET", "/v1/batteries"),
    ("POST", "/v1/batteries"),
    ("GET", "/v1/batteries/{battery_id}"),
    ("DELETE", "/v1/batteries/{battery_id}"),
    ("GET", "/v1/batteries/{battery_id}/scripts"),
    (
        "POST",
        "/v1/batteries/{battery_id}/scripts/{script_id}/install",
    ),
    ("POST", "/v1/batteries/{battery_id}/sync"),
    ("GET", "/v1/secrets"),
    ("GET", "/v1/node/status"),
    ("GET", "/v1/node/discovery"),
    ("POST", "/v1/node/init"),
    ("GET", "/v1/node/health"),
    ("GET", "/v1/node/signals"),
    ("POST", "/v1/node/cues"),
    ("POST", "/v1/node/baselines"),
    ("POST", "/v1/node/baseline/rollback"),
    ("GET", "/v1/node/peers"),
    ("POST", "/v1/node/peers"),
    ("GET", "/v1/node/enrollments"),
    ("POST", "/v1/node/enrollments"),
    ("POST", "/v1/node/enrollments/{node_id}/approve"),
    ("POST", "/v1/node/enrollments/{node_id}/reject"),
    ("POST", "/v1/node/enrollment/bundle"),
    ("PATCH", "/v1/node/peers/{node_id}/capabilities"),
    ("POST", "/v1/node/peers/{node_id}/revoke"),
];

// OMAKURE_HTTP_ROUTE_INVENTORY_END
